name: 'marketing_analytics'
version: '1.0.0'
config-version: 2

profile: 'marketing_analytics'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

vars:
  client_id: 'client1'

models:
  marketing_analytics:
    staging:
      +materialized: view
      +schema: staging
    marts:
      +materialized: table
      +schema: marts
      core:
        +schema: marts
      marketing:
        +schema: marts

seeds:
  marketing_analytics:
    +schema: staging
